# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-30 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gasoil_today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('detail', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id_service', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('detail', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
