# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-30 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0002_gasoil_today_products_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_service',
            new_name='id_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='service_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='id_product',
            new_name='id_service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='product_name',
            new_name='service_name',
        ),
    ]
